name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    - name: Archive output artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: output
        path: |
          build
        retention-days: 2
    
    - name: Get Vars
      id: vars
      run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apexsky_kvm_${{ steps.vars.outputs.sha_short }}_b${{ github.run_number }}
        path: |
          build/apex_dma
          build/libmemflow_qemu.x86_64.so
          libs/libmicrovmi.so
          libs/leechcore_device_microvmi.so
          libs/vmm.so
          libs/leechcore.so
          README.md
        retention-days: 5
